language: python
sudo: false
cache:
  directories:
    - ~/.cache/pip
env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
addons:
  apt:
    packages:
    - libgdal1h
    - gdal-bin
    - libgdal-dev
    - libatlas-dev
    - libatlas-base-dev
    - gfortran
python:
  - "2.7"
  - "3.5"
before_install:
  - "pip install -U pip"
  - "pip install wheel"
  - "pip install coveralls"
install:
  - "pip wheel numpy"
  - "pip install --use-wheel numpy cython"
  - "pip install 'rasterio==1.0a1' --no-binary rasterio"
  - "pip wheel -r requirements.txt"
  - "pip install --use-wheel -r requirements.txt"
  - "pip install -e .[test]"
script:
  - py.test --cov rio_cloudmask --cov-report term-missing
after_success:
  - coveralls
